name: fib_online_payment
description: A Flutter package for handling FIB Online Payments, including authentication, payment creation, cancellation, status checks, and refunds.
version: 1.1.2
homepage: https://github.com/First-Iraqi-Bank/fib-flutter-payment-sdk
repository: https://github.com/First-Iraqi-Bank/fib-flutter-payment-sdk.git

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  http: ^1.3.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  flutter_lints: ^5.0.0