name: Publish to pub.dev

on:
  push:
    tags:
      - 'v*'  # Triggers on tags like v1.0.0, v1.1.0, etc.

jobs:
  publish:
    permissions:
      id-token: write  # Required for OIDC authentication
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
